repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

charts:
  - name: dev-catalog-rest-api
    namespace: dev-catalog-app
    chart: ../../charts/catalog-rest-api/
    values:
      - ../../values/dev/catalog-rest-api/values.yaml
  - name: dev-catalog-storage-service
    namespace: dev-catalog-app
    chart: ../../charts/catalog-storage-service/
    values:
      - ../../values/dev/catalog-rest-api/values.yaml
  - name: dev-catalog-enricher-service
    namespace: dev-catalog-app
    chart: ../../charts/catalog-enricher-service/
    values:
      - ../../values/dev/catalog-enricher-service/values.yaml
